security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    enable_authenticator_manager: true

    providers:
        app_user_provider:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login_ldap:
                login_path: login
                check_path: login
                service: Symfony\Component\Ldap\Ldap
                dn_string: '%env(resolve:LDAP_BASE_DN)%'
                query_string: '(&(objectClass=user)(samaccountname={username}))'
                search_dn: '%env(resolve:LDAP_SEARCH_DN)%'
                search_password: '%env(LDAP_SEARCH_PASSWORD)%'
            logout:
                path: logout

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
